# -*- coding: utf-8 -*-
import io, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(HERE, "overrides.json")
ov = json.load(io.open(p, encoding="utf-8"))
ov.update({
"Y1166": {"claim": "The earlier 84 -> 13 printings mixed seeds: 84 at seeds 1 and 2024, 13 at seed 606, with no single seed yielding both",
"verdict": "CONFIRMED", "method": "measurement (parent recheck: `p3_relabel_pergood.py` re-run at seeds 1, 2024 and 606 with the first-order configuration at the HiGHS default tolerance as well as pinned)",
"ev": "Rechecked personally, overturning a subagent PARTIAL that had measured the first-order configuration only with the tolerance pinned. Patching the hardcoded seed (20260821) and adding a first-order/default-tolerance configuration gives, at the HiGHS default tolerance: seed 1 -> first-order 84 of 290, full cost 11; seed 2024 -> first-order 84, full cost 11; seed 606 -> first-order 86, full cost 13. So 84 appears at seeds 1 and 2024, 13 at seed 606, and no seed yields both - exactly as claimed. (With the tolerance pinned the first-order figures instead read 85, 89 and 87, which is how the disagreement arose, and is itself the point the neighbouring sentence makes.)"},
"Y1169": {"claim": "The copper flip count over four column permutations is seed-dependent, taking the values 2, 8 or 6",
"verdict": "PARTIAL", "method": "measurement (parent recheck: `round6.py`'s exact permutation mechanism swept over seeds 0-30)",
"ev": "Rechecked personally, softening a subagent REFUTED. Seed-dependence is confirmed and is the load-bearing half (it is why no single count is quoted). The enumerated set is wrong: replicating round6.py's mechanism exactly - identity plus four `default_rng(seed).permutation(len(ARCS))` column orders, counting distinct (permutation, edge-slot) flips against the identity solve at the HiGHS default tolerance - over seeds 0-30 gives {4, 6, 8, 10, 12, 14}, with 8 most common (11 of 31), 10 next (8 of 31), and **2 never observed**. Per-seed: 0->10, 1->4, 2->6, 3->8, 4->8 (the shipped seed, matching round6.py's printed 8), 5->10, 13->12, 16->14, 17->14, 29->14, 30->12."},
"Y1030": {"claim": "The solver's optimality tolerance is a correctness requirement rather than a performance knob, and HiGHS stops when reduced costs are within its dual feasibility tolerance of zero",
"verdict": "PARTIAL", "method": "file read (parent recheck: scipy 1.18.0 `_linprog_doc.py`) + measurement (the tolerance bisection in `round6.py`)",
"ev": "Rechecked personally. The correctness half is established behaviourally: on `copper`, whose margin is 3.765e-08, an unset tolerance and 1e-7 give identical flip sets over four column permutations while 1e-8 and 1e-10 give none (`r6.out`), so the tolerance decides which vertex is returned. The stopping-rule half is not settleable from the materials: scipy 1.18.0's `_linprog_doc.py` documents only the option and its value - \"dual_feasibility_tolerance : double (default: 1e-07) Dual feasibility tolerance for 'highs-ds'\" - and states no termination test; HiGHS's own source and documentation are not in the install or the tree. What would settle it: the HiGHS source or its solver documentation."},
"Y476": {"claim": "Neither coefficient is read off a province window, because a window figure carries the owner's modifiers and some of those are randomised at game start",
"verdict": "CONFIRMED", "method": "file read (parent recheck: `history/countries/GRA - Granada.txt`, `common/ruler_personalities/00_core.txt`)",
"ev": "Rechecked personally, overturning a subagent PARTIAL that could not source the randomisation half. `GRA - Granada.txt` contains zero occurrences of `personality`; its 1444 monarch is the `1419.1.1`-era `monarch = { name = \"Muhammad IX\" dynasty = \"Nasrid\" adm 1 dip 1 mil 0 }` with no personality key. `common/ruler_personalities/00_core.txt` carries 191 `chance = { }` blocks - one per personality's `ruler_allow`, e.g. `industrious_personality` at line 1359 - which is the roll table the engine draws from where history scripts none. `industrious_personality` grants `global_trade_goods_size_modifier = 0.1`, exactly the +10% that reconciles Garnatah's window Trade Value 3.52 with 0.80 x 4.00 = 3.20. So a window figure does carry an owner modifier that is randomised at game start."},
"Y631": {"claim": "Node-level alpha overweights a k-province node by k^(alpha-1); at alpha(g)=1.5 the comparisons give ~2x and ~1.44x, at alpha_Phi=2.0 they give 4.1x and 2.1x, so the slicing distortion is larger on the aggregate graph than on any per-good one",
"verdict": "PARTIAL", "method": "derivation check + file read (parent recheck: `common/prices/00_prices.txt`, the shipped alpha formula)",
"ev": "Rechecked personally. The algebra and all four multipliers are right: (77/19)^0.5 = 2.01, (68/33)^0.5 = 1.436, 77/19 = 4.05, 68/33 = 2.06. The closing conclusion is false. The shipped alpha is `max(0.2, min(3.0, price/2.0))`, so any good priced at or above 6.0 clamps to alpha = 3.0 and carries exponent alpha-1 = 2.0, against alpha_Phi = 2.0's exponent of 1.0. `cloves` is priced 8.0 in `common/prices/00_prices.txt` and is one of the 29 live 1444 goods (it is the single-producer good `m6.out` names), giving alpha 3.00 and exponent 2.00; the same two node comparisons then read (77/19)^2 = 16.4x and (68/33)^2 = 4.25x, both larger than the aggregate's. `coal` (10.0) is the same but latent. So a live good on the same field carries a bigger slicing distortion than the aggregate graph does."},
})
json.dump(ov, io.open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("overrides:", len(ov))
