# -*- coding: utf-8 -*-
import io, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(HERE, "overrides.json")
ov = json.load(io.open(p, encoding="utf-8"))
ov.update({
"Y214": {"claim": "The claim-audit corrections from ../v1-laplacian/validation.md settleable from files were folded in at v2 and carried since, spot-verified on 7 of 60 with none missing",
"verdict": "PARTIAL", "method": "file read (parent recheck: `../v1-laplacian/validation.md` status table; the round-7 artifacts)",
"ev": "Rechecked personally. The denominator is confirmed: `../v1-laplacian/validation.md`'s own status table (L15-23) gives CONFIRMED 276, REFUTED 23, PARTIAL 37, NEEDS_GAME 49, OUT_OF_SCOPE 208, DEFERRED 92, total 685 - and 23 + 37 = **60**, exactly the corrections the sentence counts against. A sample of those corrections (the node-size spread, the supply-range wording, the autonomy floor, the trade-power bands, plus the grain/livestock price misreads and the Propagate Religion gating, all named in SS3.16) is present and carried in the current text. What the claim outruns is verification of its own spot-check: no artifact in `fixes-round7.md`, `claims-delta-round7.md`, `round7.diff` or the round-7 working tree records which 7 of the 60 were checked or what each returned (that self-report is graded separately as Y1142, UNTESTABLE), and the sentence itself concedes no exhaustive re-check exists."},
"Y665": {"claim": "Per-good eligibility returns true for some goods at every node, so no nation is ever globally inert",
"verdict": "PARTIAL", "method": "measurement (parent recheck: out-degree per node across all 29 per-good DRAIN orientations)",
"ev": "Rechecked personally. The node-level half is confirmed exactly: running DRAIN on all 29 live goods, **no node has out-degree 0 for every good** - the minimum number of goods giving a node an outgoing arc is **18** and the maximum is 29, and 30 of the 80 nodes are a sink for at least one good. What the claim outruns is the per-*nation* universal: whether every country has at least one good for which its power counts additionally requires that country's merchant placement and collection points, which the reference implementation does not model and no shipped instrument computes. The node-level fact is necessary for the nation-level conclusion, not sufficient for it."},
"Y695": {"claim": "AI light-ship building, trade-league behaviour, peace valuation and income-threshold events all read the engine's node value figures",
"verdict": "PARTIAL", "method": "file read (parent recheck: search of `common/`, `events/` for trade-income consumers and light-ship defines)",
"ev": "Rechecked personally. The income-threshold half is file-confirmed: `trade_income_percentage` is read by shipped scripted content - `common/church_aspects/02_anglican_aspects.txt`, `common/decrees/00_china.txt`, `common/estates/003_vaisyas.txt`, `common/estates/03_burghers.txt`, `common/estate_agendas/003_vaisya_agendas.txt` among others. The other three consumers are engine-internal AI behaviours: `common/defines.lua` exposes only light-ship cost and maintenance constants (LIGHT_SHIP_COST 20 at L1334, LIGHT_SHIP_MAINT_FACTOR 0.03 at L1173, LIGHT_SHIP_TIME 365 at L1341, LIGHT_SHIP_SAILORS_COST 50 at L1310), never a rule tying the build decision to node value, and no shipped file states the trade-league or peace-valuation inputs. Settling those three needs the disassembly SS2.7 item 10 specifies."},
"Y503": {"claim": "The binary is frozen - offsets found stay found",
"verdict": "PARTIAL", "method": "file read (parent recheck: `eu4_rev.txt`, `clausewitz_rev.txt`, the three crash dumps' `meta.yml`)",
"ev": "Rechecked personally. Stability across the observed window is confirmed: `eu4_rev.txt` and `clausewitz_rev.txt` both read `835bfdf8ca24c291a1b3f1b5bc72d47e7df1ae18`, and all three crash dumps' `meta.yml` carry the same `SCMCommit: 835bfdf8ca24c291a1b3f1b5bc72d47e7df1ae18` with `SCMTimeStamp: \"2024-10-03 10:50:26 +0200\"`, across launches three hours apart, while the fault address `0x00007FF6DDE6A8B4` is byte-identical in all three. What cannot be tested is the unqualified permanence the sentence asserts: no second build of EU4 exists in these materials, so \"offsets found stay found\" holds for 1.37.5 and is untested against any future patch - which is the scope the sentence does not state."},
})
json.dump(ov, io.open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("overrides:", len(ov))
