// THE DRAWN ARROWS (spec 1.12 "Φ_w remains the drawn installed direction"; tests B1, F1, D1).
//
// The arrow layer is built by BuildTradeRouteLayer(mapRenderer) = eu4.exe+0x10AFA70, which
// destroys every existing route object and regenerates one CTradeRoute per outgoing entry of
// every trade-node definition. Two facts make runtime re-orientation possible:
//
//   * the ribbon geometry is generated by walking the outgoing entry's polyline at entry+0x58
//     from index 0 upward (0x13F6362), so REVERSING that float2 array reverses the drawn arrow
//     without touching the link's economic identity (entry+0x30, the target definition, and the
//     entry's position in def+0x98, both stay put);
//   * 0x10AFA70 is idempotent and callable on demand, so the layer can be rebuilt whenever the
//     monthly re-solve changes the orientation.
//
// Hard limit (spec 2.4 / probe 13): a route exists only for an edge declared in
// 00_tradenodes.txt, and the engine hard-crashes on a cyclic file, so a link is declared exactly
// once. Runtime views may therefore REVERSE or hide a route, never add one -- which is exactly
// what the emitted file plus this reversal gives: every physical link, drawn in whichever
// direction the current solve says.
//
// mapRenderer is captured by detouring 0x10AFA70 once at attach (the original still runs via the
// trampoline), because the pointer is not reachable from any static we have.
#pragma once
#include <windows.h>
#include <atomic>
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>
#include "detour.h"
#include "livetrade.h"

namespace arrows {

constexpr uintptr_t BUILD_LAYER   = 0x10AFA70;   // BuildTradeRouteLayer(mapRenderer)
constexpr uintptr_t DEF_VECTOR    = 0x242BE48;   // {begin,end} vector<CTradeNodeDefinition*>
constexpr int DEF_OUT_BEGIN       = 0x98;        // outgoing entries, stride 0x78
constexpr int DEF_OUT_END         = 0xA0;
constexpr int OUT_STRIDE          = 0x78;
constexpr int OUT_TARGET_DEF      = 0x30;        // the entry's destination definition
constexpr int OUT_POLY_BEGIN      = 0x58;        // float2 polyline {begin,end}
constexpr int OUT_POLY_END        = 0x60;
constexpr int DEF_NODE_INDEX      = 0xD8;

inline std::atomic<uintptr_t> g_map_renderer{0};
inline detour::Hook g_capture;
inline std::string g_log;

// which entries we have reversed, so a re-orientation only flips what actually changed
inline std::set<uintptr_t> g_reversed;

inline void capture_handler(detour::Regs* r) {
    if (!g_map_renderer) g_map_renderer = r->rcx;
}

inline bool install_capture(std::string* err) {
    uintptr_t site = livetrade::module_base() + BUILD_LAYER;
    std::vector<uint8_t> expected{
        0x48, 0x89, 0x4c, 0x24, 0x08,               // mov [rsp+8], rcx
        0x53, 0x55, 0x56, 0x57,                     // push rbx,rbp,rsi,rdi
        0x41, 0x54, 0x41, 0x55, 0x41, 0x56, 0x41, 0x57,  // push r12..r15
        0x48, 0x81, 0xec, 0x88, 0x00, 0x00, 0x00};  // sub rsp,0x88
    if (!detour::install(g_capture, site, expected, &capture_handler, "trade_route_layer")) {
        if (err) *err = g_capture.error;
        return false;
    }
    return true;
}

inline std::string g_def_source;   // which layout worked, for the log

// Does this object look like a CTradeNodeDefinition? Validated by STRUCTURE, not by vtable:
// vtable 0x1C439D0 turned out to belong to the outgoing LINK ENTRY class (objects at stride 0x78
// carrying the destination node's name at +0x10), so filtering definitions on it rejected the
// real ones. A definition has a node index at +0xD8 and an outgoing {begin,end} vector at
// +0x98/+0xA0 whose span is a whole number of 0x78-byte entries (possibly zero, for a sink).
inline bool struct_is_definition(uintptr_t d) {
    if (!livetrade::validate_region(d + DEF_NODE_INDEX, 4)) return false;
    int idx = livetrade::fi(d + DEF_NODE_INDEX);
    if (idx < 0 || idx >= 512) return false;
    if (!livetrade::validate_region(d + DEF_OUT_BEGIN, 16)) return false;
    uintptr_t ob = livetrade::fq(d + DEF_OUT_BEGIN), oe = livetrade::fq(d + DEF_OUT_END);
    if (oe < ob) return false;
    size_t span = oe - ob;
    if (span % OUT_STRIDE || span > OUT_STRIDE * 64) return false;
    if (span && !livetrade::validate_region(ob, span)) return false;
    return true;
}

// Try one {begin,end} pair as a vector<CTradeNodeDefinition*>.
inline bool try_vector(uintptr_t vb, std::vector<uintptr_t>& out) {
    if (!livetrade::validate_region(vb, 16)) return false;
    uintptr_t begin = livetrade::fq(vb), end = livetrade::fq(vb + 8);
    if (!begin || end <= begin || (end - begin) > 8 * 4096 || ((end - begin) % 8)) return false;
    if (!livetrade::validate_region(begin, end - begin)) return false;
    std::vector<uintptr_t> tmp;
    int good = 0, total = 0;
    for (uintptr_t p = begin; p + 8 <= end; p += 8) {
        uintptr_t d = livetrade::fq(p);
        total++;
        if (!d || !livetrade::validate_region(d, 8)) continue;
        if (struct_is_definition(d)) { good++; tmp.push_back(d); }
    }
    if (good >= 40 && good * 2 >= total) { out = tmp; return true; }
    return false;
}

// Enumerate the definition objects. The .data slot at 0x242BE48 did not hold the vector in any
// of the plausible layouts (checked live: inline, pointer, pointer+8, and the database head), so
// the definitions are found the way the node names already are -- a heap scan for objects whose
// first qword is the CTradeNodeDefinition vtable, then filtered to those that really carry a node
// index and an outgoing-link vector. The result is CACHED: definitions are created once at load
// and never move, so the scan happens a single time.
inline std::vector<uintptr_t> g_defs_cache;

inline bool looks_like_definition(uintptr_t d) {
    if (!livetrade::validate_region(d + DEF_NODE_INDEX, 4)) return false;
    int idx = livetrade::fi(d + DEF_NODE_INDEX);
    if (idx < 0 || idx >= 512) return false;
    if (!livetrade::validate_region(d + DEF_OUT_BEGIN, 16)) return false;
    uintptr_t ob = livetrade::fq(d + DEF_OUT_BEGIN), oe = livetrade::fq(d + DEF_OUT_END);
    if (oe < ob) return false;
    size_t span = oe - ob;
    if (span % OUT_STRIDE || span > OUT_STRIDE * 64) return false;
    return true;
}

// Dump the raw layout of a few real definition objects, so the outgoing-list and node-index
// offsets are READ rather than assumed. A definition is identified by its vtable and by having a
// readable node name (inline std::string at +0x10), exactly as the node-name scan already does.
inline void dump_definition_layout(const std::string& logpath, int how_many = 3) {
    std::ofstream log(logpath, std::ios::app);
    log << "--- CTradeNodeDefinition raw layout (vtable-scanned objects) ---\n";
    uintptr_t defvt = livetrade::module_base() + 0x1C439D0;
    int shown = 0;
    livetrade::walk_self([&](uintptr_t region, size_t sz) {
        if (shown >= how_many) return;
        const uint8_t* p = (const uint8_t*)region;
        for (size_t i = 0; i + 0x140 <= sz && shown < how_many; i += 8) {
            uintptr_t vt;
            memcpy(&vt, p + i, 8);
            if (vt != defvt) continue;
            uintptr_t d = region + i;
            // read the inline std::string name at +0x10 to confirm this is a real definition
            char nm[17] = {0};
            memcpy(nm, p + i + 0x10, 16);
            size_t len = strnlen(nm, 16);
            std::string name(nm, len);
            bool ok = !name.empty();
            for (char c : name) if (!((c >= 'a' && c <= 'z') || c == '_' || (c >= '0' && c <= '9'))) ok = false;
            if (!ok) continue;
            log << "  def '" << name << "' @0x" << std::hex << d << std::dec << "\n";
            for (int off = 0x00; off <= 0x78; off += 8) {
                uintptr_t q; memcpy(&q, p + i + off, 8);
                int32_t lo; memcpy(&lo, p + i + off, 4);
                int32_t hi; memcpy(&hi, p + i + off + 4, 4);
                const char* tag = "";
                // a {begin,end} pair whose span divides 0x78 is an outgoing-link vector
                uintptr_t nxt; memcpy(&nxt, p + i + off + 8, 8);
                if (q && nxt > q && (nxt - q) <= 0x78 * 32 && ((nxt - q) % 0x78) == 0) tag = "  <-- {begin,end} stride 0x78";
                if (q && nxt > q && (nxt - q) <= 8 * 32 && ((nxt - q) % 8) == 0 && (nxt - q) > 0) tag = "  <-- {begin,end} stride 8";
                log << "    +0x" << std::hex << off << " = 0x" << q << std::dec
                    << "  (i32 " << lo << ", " << hi << ")" << tag << "\n";
            }
            shown++;
        }
    });
}

inline std::vector<uintptr_t> definitions() {
    if (!g_defs_cache.empty()) return g_defs_cache;
    uintptr_t base = livetrade::module_base();
    // FIRST: the vector the engine's own arrow builder reads (0x10AFAA4). Now validated by
    // structure, which is what made it match.
    {
        std::vector<uintptr_t> v;
        uintptr_t slot = base + DEF_VECTOR;
        if (try_vector(slot, v)) { g_defs_cache = v; g_def_source = "vec@0x242BE48"; return g_defs_cache; }
        uintptr_t obj = livetrade::validate_region(slot, 8) ? livetrade::fq(slot) : 0;
        if (obj && try_vector(obj, v)) { g_defs_cache = v; g_def_source = "ptr@0x242BE48"; return g_defs_cache; }
    }
    // FALLBACK: scan the heap for objects that structurally look like definitions, reached from
    // the link entries (whose vtable we do know).
    uintptr_t entryvt = base + 0x1C439D0;   // outgoing link-entry vtable
    std::vector<uintptr_t> found;
    livetrade::walk_self([&](uintptr_t region, size_t sz) {
        const uint8_t* p = (const uint8_t*)region;
        for (size_t i = 0; i + 0x100 <= sz; i += 8) {
            uintptr_t vt;
            memcpy(&vt, p + i, 8);
            if (vt != entryvt) continue;
            uintptr_t d = region + i;
            if (struct_is_definition(d)) found.push_back(d);
        }
    });
    // keep one object per node index (the scan can see stale or template copies)
    std::map<int, uintptr_t> byidx;
    for (uintptr_t d : found) {
        int idx = livetrade::fi(d + DEF_NODE_INDEX);
        uintptr_t ob = livetrade::fq(d + DEF_OUT_BEGIN), oe = livetrade::fq(d + DEF_OUT_END);
        auto it = byidx.find(idx);
        // prefer the copy that actually has outgoing links
        if (it == byidx.end() || (oe > ob)) byidx[idx] = d;
    }
    for (auto& [idx, d] : byidx) g_defs_cache.push_back(d);
    g_def_source = "vtable scan (" + std::to_string(g_defs_cache.size()) + " defs)";
    return g_defs_cache;
}

inline int def_node_index(uintptr_t def) {
    if (!livetrade::validate_region(def + DEF_NODE_INDEX, 4)) return -1;
    return livetrade::fi(def + DEF_NODE_INDEX);
}

// reverse an outgoing entry's polyline in place (float2 = 8 bytes per point)
inline bool reverse_polyline(uintptr_t entry) {
    if (!livetrade::validate_region(entry + OUT_POLY_BEGIN, 16)) return false;
    uintptr_t b = livetrade::fq(entry + OUT_POLY_BEGIN);
    uintptr_t e = livetrade::fq(entry + OUT_POLY_END);
    if (!b || e <= b) return false;
    size_t bytes = e - b;
    if (bytes % 8 || bytes > 1 << 20) return false;
    if (!livetrade::validate_region(b, bytes)) return false;
    size_t n = bytes / 8;
    DWORD old = 0;
    if (!VirtualProtect((void*)b, bytes, PAGE_READWRITE, &old)) return false;
    uint64_t* pts = (uint64_t*)b;
    for (size_t i = 0; i < n / 2; i++) {
        uint64_t t = pts[i];
        pts[i] = pts[n - 1 - i];
        pts[n - 1 - i] = t;
    }
    VirtualProtect((void*)b, bytes, old, &old);
    return true;
}

// Make the drawn arrows match `desired` (a directed edge set over engine NODE INDICES).
// Returns the number of routes whose drawn direction was changed.
// diagnostics from the last set_directions() call
inline int g_defs_seen = 0, g_entries_seen = 0, g_matched_fwd = 0, g_matched_rev = 0, g_unmatched = 0;

inline int set_directions(const std::set<std::pair<int, int>>& desired) {
    int changed = 0;
    g_defs_seen = g_entries_seen = g_matched_fwd = g_matched_rev = g_unmatched = 0;
    for (uintptr_t def : definitions()) {
        g_defs_seen++;
        int src = def_node_index(def);
        if (src < 0) continue;
        if (!livetrade::validate_region(def + DEF_OUT_BEGIN, 16)) continue;
        uintptr_t ob = livetrade::fq(def + DEF_OUT_BEGIN);
        uintptr_t oe = livetrade::fq(def + DEF_OUT_END);
        if (!ob || oe <= ob) continue;
        size_t span = oe - ob;
        if (span % OUT_STRIDE || span > OUT_STRIDE * 64) continue;
        if (!livetrade::validate_region(ob, span)) continue;
        for (uintptr_t entry = ob; entry + OUT_STRIDE <= oe; entry += OUT_STRIDE) {
            uintptr_t tdef = livetrade::fq(entry + OUT_TARGET_DEF);
            if (!tdef) continue;
            int dst = def_node_index(tdef);
            if (dst < 0) continue;
            g_entries_seen++;
            // the file declares src->dst. Should the arrow point that way?
            bool declared_ok = desired.count({src, dst}) > 0;
            bool wants_reverse = !declared_ok && desired.count({dst, src}) > 0;
            if (declared_ok) g_matched_fwd++;
            else if (wants_reverse) g_matched_rev++;
            else g_unmatched++;
            bool is_reversed = g_reversed.count(entry) > 0;
            if (wants_reverse != is_reversed) {
                if (reverse_polyline(entry)) {
                    if (wants_reverse) g_reversed.insert(entry);
                    else g_reversed.erase(entry);
                    changed++;
                }
            }
        }
    }
    return changed;
}

// Rebuild the whole layer. MUST run on the game thread (it destroys and creates render objects),
// so call it from the tick hook, never from a worker.
inline bool rebuild() {
    uintptr_t mr = g_map_renderer.load();
    if (!mr) return false;
    using Fn = void(__fastcall*)(uintptr_t);
    Fn f = (Fn)(livetrade::module_base() + BUILD_LAYER);
    f(mr);
    return true;
}

} // namespace arrows
