# -*- coding: utf-8 -*-
"""v6 batch 23 — S06, the §3.10 rewrite. Third revision of this paragraph, and the first whose
central claim is provable rather than measured: the single node scalar does reproduce every
collector's income exactly, and what per-good propagation actually costs is that the scalar stops
being derivable from trade power alone."""
import io, patch_lib
old = io.open(r"C:\Users\rdavi\.claude\jobs\f8a5d44b\tmp\p310b.txt", encoding="utf-8").read()
new = """**This is also why propagation is kept on a single graph — and the reason is not the one v1 through v6.0's own first draft gave.** Reading the one installed graph leaves the propagated term good-independent, so the identity holds by construction, and in doubles to within one to three units in the last place. Per-good propagation makes a country's power at the node differ by good, because §1.9 reads a node's downstream neighbours and those differ per good: `gulf_of_siam`'s 29 goods leave it by **seven** distinct downstream sets. **What that does *not* do is break the identity.** Define `ps̄_C = Σ_g v_g·cs_g·ps_C(g) / Σ_g v_g·cs_g` — the per-good shares weighted by *collected* value — and `collect_pool · ps̄_C = income_C` follows algebraically, with `Σ_C ps̄_C = 1`, so `ps̄_C` is a legal share vector and one scalar per node still reproduces every collector's income exactly. Both inputs already exist per good at write time; §2.6 sums exactly them into `collect_pool`.

**The real cost is that `ps̄_C` is not derivable from trade power alone.** It is value-weighted, so installing it means writing a country a fictitious per-node trade power whose ratio happens to equal it — and every other consumer of that power field then reads the fiction. That is a claim about what the engine exposes, not about a magnitude, and it is why the single graph stays: on one graph the scalar *is* the country's power share, needing no invention. *(The magnitudes previous versions quoted were all artifacts of substituting some other weighting. v1 through v4.0: "off by 5.96 ducats on a node paying ~250", where no node in the model has local trade value near 250. v4.0: 0.41%. v5.0: "redistributive and single-digit percent". v6.0's first draft: "at most 0.1%". Each froze or reweighted the share differently — gross-value weighting alone ranges from 0.00% to 4.6% across collector sets on this field, and up to 49% in general — so each measured its own construction. No figure is quoted here, because the identity holds and the objection is structural.)*"""
patch_lib.apply([dict(id="S06", clears="S06: the identity is not broken; the scalar's provenance is the cost",
                      section="3.10", old=old, new=new)])
