# -*- coding: utf-8 -*-
import io, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(HERE, "overrides.json")
ov = json.load(io.open(p, encoding="utf-8"))
ov.update({
"Y972": {"claim": "The 1444 sink set moves from {english_channel, hangzhou} to {genua, hangzhou} when alpha_Phi moves 1.5 -> 2.0",
"verdict": "PARTIAL", "method": "measurement (parent recheck: alpha_Phi sweep on the shipped operator) + file read (`changes-v6.md`)",
"ev": "Rechecked personally, softening a subagent REFUTED. Destination confirmed: alpha_Phi=2.0 gives {genua, hangzhou} (`m6.out`). Origin not reproducible on this field with the shipped tie-broken solver: alpha_Phi=1.5 gives a SINGLE sink, {english_channel}. My sweep: 1.0 -> {english_channel, gulf_of_siam, mexico}; 1.4 -> {english_channel, hangzhou, rheinland}; 1.5 -> {english_channel}; 1.6 -> {genua}; 1.63 -> {genua, hangzhou}. Consistent with the document's own count row [3, 1, 2, 2, 1, 1] at alpha in {1,1.5,2,3,4,8} (spec L611, `m6.out`). As a version-to-version changelog statement it is corroborated - `changes-v6.md:71` and `:272` record the pre-change installed ends as {english_channel, hangzhou} - because v6.1 bundled alpha_Phi 1.5->2.0 with the Phase-2 tie-break, and it is the tie-break that moved the 1.5 answer. What fails is the sentence read as alpha_Phi's own effect on this field."},
"Y017": {"claim": "Some figures carry a script attribution instead of a guard, and some carry neither",
"verdict": "CONFIRMED", "method": "file read (spec L96-97) + measurement (`coverage6.py`, `verify6.py` on the current spec)",
"ev": "Rechecked personally, overturning a subagent PARTIAL that graded the inventory label's wording (\"a few\") rather than the document's. Spec L96-97 reads \"Some figures carry a script attribution instead of a guard, and some carry neither\" - both quantifiers are \"some\". Fresh runs: `verify6.py ../per-good-trade-spec.md` -> \"RESULT: 36 checks, 0 failed\"; `coverage6.py ../per-good-trade-spec.md` -> \"coverage: 4 of 6 uniquely-locatable spec figures are protected (67%)\". Both halves hold."},
"Y011": {"claim": "The rejected-operator numbers were re-measured and re-refuted in three successive audits, and no rejection argument depends on them",
"verdict": "PARTIAL", "method": "file read (parent recheck: the three prior-version validation files)",
"ev": "Rechecked personally. `../v3-owner-agnostic/validation-v3.md` (laplacian x6, RANK x1, gravity x1) and `../v5-owner-agnostic/validation-v5.md` (laplacian x2, RANK x8, gravity x2) do re-examine them. `../v4-owner-agnostic/validation-v4.md` has zero occurrences of \"laplacian\", \"RANK\" or \"basin\" and exactly one gravity row - L164, W190, \"The gravity kernel's 'hits any chosen end count exactly' gains its gamma range\", verdict PASS. A PASS is not a re-refutation, so \"re-refuted in three successive audits\" outruns the middle audit. The independence half holds: SS3.15's entries argue from structure (pinned end count, a second operator with its own reach knob, monotone local comparison) with no figure load-bearing."},
"Y177": {"claim": "mexico (300.4, 2nd), gulf_of_siam (297.9, 3rd) and sevilla (266.5, 7th) are net demanders with flow still passing through them",
"verdict": "PARTIAL", "method": "measurement (parent recheck: aggregate min-cost b-flow, per-node flow_in/flow_out)",
"ev": "Rechecked personally. Wealth figures reproduce exactly (english_channel 316.6 rank 1, mexico 300.4 rank 2, gulf_of_siam 297.9 rank 3, genua 296.0 rank 4, sevilla 266.5 rank 7). The flow half fails for two of the three: mexico has flow_in 0.0110 / flow_out 0.0000 at out-degree 1, gulf_of_siam flow_in 0.0156 / flow_out 0.0000 at out-degree 1 - both are members of the \"18 of 80 nodes with out-degree above zero carrying no outgoing flow at all\" the same paragraph counts. Only sevilla passes flow on: flow_in 0.0324, flow_out 0.0201. (english_channel, named in the preceding sentence, is likewise flow_out 0.0000 at out-degree 3.) The identity flow_in - flow_out = -b_w holds on 80 of 80 nodes to 5.2e-17."},
"Y438": {"claim": "Solver item 2 is a parser for non-ironman saves reading province owner, base_tax, base_production, trade good, goods produced and development",
"verdict": "PARTIAL", "method": "file read (parent recheck: `solver.py`, `provinces.py`, tree-wide grep for zipfile/gamestate)",
"ev": "Rechecked personally, softening a subagent REFUTED because the row is a DESIGN stipulation. As a stipulation it stands. What fails is SS2.2's own characterisation of the list - \"The list above is the reference solver: standalone, run against parsed saves\". The reference solver builds its province table from `history/provinces` via `provinces.py` (docstring: \"Build the 1444.11.11 province dataset from history/provinces\"), and the only save read on the solve path is `solver.py::_rolled_trade_goods()`, which opens `VANILLA_start.eu4` and extracts `trade_goods` alone for the 20 unknown-good provinces. No owner, base_tax, base_production, goods-produced or development field is read from a save on that path; the save-reading scripts that do exist (`audit_delta.py`, `audit_f4.py`, `p3_wealth.py`, `preconfirm3.py`) are audit instruments, not the solver."},
"Y439": {"claim": "Solver item 3 is a parser for common/defines.lua merged with common/defines/ overrides in load order",
"verdict": "PARTIAL", "method": "file read (parent recheck: tree-wide grep for defines.lua and common/defines/ across `scripts/`)",
"ev": "Rechecked personally, softening a subagent REFUTED. The stipulation stands and the document itself flags it as unbuilt - SS2.9 says the defines parser must come first because the downstream terms \"cannot be written correctly before it exists\". What exists is one ad-hoc read: `measure6.py:252` opens `common/defines.lua` and regexes out three constants (TRADING_POLICY_COOLDOWN_MONTHS, TRADE_COMPANY_DAYS_TO_SWAP_LEADER, TRADE_COMPANY_COOLDOWN). Nothing in `scripts/` merges `common/defines/` overrides in load order, and that directory is non-empty in 1.37.5 (00_dummy.lua, difficulty_*.lua). `solver.py` hardcodes TAX_COEFF and reads GP_COEFF from `00_static_modifiers.txt`, not from defines."},
"Y444": {"claim": "Solver item 6 is a survival table S_g[n][H] for AI scoring, one table serving every country",
"verdict": "PARTIAL", "method": "file read (parent recheck: tree-wide grep of `scripts/*.py` for survival / S_g)",
"ev": "Rechecked personally, softening a subagent REFUTED. The stipulation stands, and SS3.14 derives its size (29 x 80 x 80 x 8 bytes = 1,484,800). No implementation exists: grep over `scripts/*.py` finds \"survival\" only in the round-6 working files v61d/g/q/s/t.py, never in `solver.py`, `drain.py`, `flowop.py` or `measure6.py`, and no such table is built or dumped anywhere. SS2.9's build order lists it as still to be written."},
"Y437": {"claim": "Solver item 1 is a parser for 00_tradenodes.txt reading adjacency, members, path/control render data and end/inland/AI flags",
"verdict": "PARTIAL", "method": "file read (parent recheck: `nodes.py`, `nodes.json`, `common/tradenodes/00_tradenodes.txt`)",
"ev": "Rechecked personally. `nodes.py` reads outgoing names (adjacency), `members`, `inland`, `end` and `ai_will_propagate_through_trade` - four of the five groups. `path` and `control` are present in the shipped file (every `outgoing` block carries both) and are read by nothing: no node-field occurrence of either in `nodes.py`, and `nodes.json` stores neither. SS2.4 item 3 nevertheless requires the emitter to reverse both, so the render data is stipulated and unimplemented."},
"Y133": {"claim": "Repeated 12-run timing experiments do not reproduce each other; three replicates gave per-good averages spanning 3.5-10.5, 3.5-10.8 and 3.1-4.7 ms",
"verdict": "PARTIAL", "method": "measurement (parent recheck: ran the shipped `p3_time.py`, 3 replicates x 12 runs)",
"ev": "Rechecked personally. The conclusion holds and is strengthened: my three replicates gave per-good averages spanning 3.1-7.3, 4.0-6.6 and 3.7-5.0 ms (all-29 medians 0.158 / 0.144 / 0.125 s), mutually inconsistent and inconsistent with the document's. The three quoted intervals themselves do not reproduce - in particular no replicate of mine reaches the 10.5 and 10.8 ms the same paragraph uses to justify refusing the word \"single-digit\"; every per-good average I measured is single-digit milliseconds."},
"Y134": {"claim": "v5.0's 0.17-0.21 s is not reproducible: across three replicates of twelve runs the number of runs inside that interval was 1, then 0, then 0",
"verdict": "PARTIAL", "method": "measurement (parent recheck: ran the shipped `p3_time.py`, 3 replicates x 12 runs)",
"ev": "Rechecked personally. The conclusion holds: 3 of my 36 runs landed inside [0.17, 0.21] s. The specific triple does not: I measured 2, then 1, then 0 (a parallel re-run of the same instrument by a subagent measured 3, 3, 4). Three independent executions of `p3_time.py` give three different triples, which is the non-reproducibility the claim asserts - and which means the quoted 1/0/0 cannot be confirmed as stated."},
"Y365": {"claim": "SS2.7 item 11 settles the caravan recipient, and SS3.11 carries both readings of the exposure surface",
"verdict": "CONFIRMED", "method": "file read (parent recheck: spec L763-765, L1363, L1818-1821, L1865)",
"ev": "Rechecked personally, overturning a subagent PARTIAL that read \"settles\" as asserting completion. The document distinguishes tenses deliberately: SS1.7 writes \"SS2.7 item 14 settled which of those it does today\" (past, for a probe that ran) beside \"SS2.7 item 11 settles the recipient\" (present, designating the probe that will). SS3.11 L1818 uses the identical construction for an admittedly unexecuted probe - \"SS2.7 item 11 settles it with one merchant and two node windows\" - and SS3.13 L1865 lists \"the caravan recipient is pending\". SS2.7's numbered item 11 exists at L1363. The second half holds verbatim: SS3.11 L1820-1821 states both the tooltip reading (~26 inland nodes) and the v1 reading (every node adjacent to one)."},
"Y125": {"claim": "What is left exposed is everything without a cooldown, which is most of the ladder",
"verdict": "PARTIAL", "method": "file read (parent recheck: `common/trading_policies/00_trading_policies.txt`, `common/defines.lua`)",
"ev": "Rechecked personally. The damping facts hold: the policy file carries exactly 9 entries in 5 families (maximize_profit(+_upgraded), hostile_trading(+_upgraded), improve_inland_routes(+_upgraded), establish_communities(+_upgraded), propagate_religion), with `cooldown = no` on lines 25 and 52 - i.e. inside maximize_profit and maximize_profit_upgraded only - so 7 of 9 entries are rate-limited by TRADING_POLICY_COOLDOWN_MONTHS = 12 (defines.lua:1045). But \"most of the ladder\" fails on the SS1.10 table it refers to: of its 7 threshold rows, 4 are damped (Improve Inland Routes and Propagate Religion by the policy cooldown; the two trade-company rows by TRADE_COMPANY_DAYS_TO_SWAP_LEADER = 30 and TRADE_COMPANY_COOLDOWN = 60 at defines.lua:1212 and 1214) and only 3 are undamped (both trade-conflict CB rows and privateer blocking). Three of seven is not most."},
})
json.dump(ov, io.open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("overrides:", len(ov))
