# -*- coding: utf-8 -*-
"""v6 batch 9 — D1/X165/X169/X170/X171/X172: §3.10's per-good propagation restated as a loss of
exactness rather than of materiality, with the construction stated."""
import io, patch_lib
E = []
old = io.open(r"C:\Users\rdavi\.claude\jobs\f8a5d44b\tmp\p310.txt", encoding="utf-8").read()
new = """**This is also why propagation is kept on a single graph.** Reading the one installed graph leaves the propagated term good-independent, so the identity survives it untouched — worst relative disagreement 0 to 3.7e-16, which is 1.7 to 3.3 units in the last place. Per-good propagation destroys the *exactness*, because §1.9 reads a node's downstream neighbours and those differ per good: `gulf_of_siam`'s 29 goods leave it by **seven** distinct downstream sets. Once they differ, a country's power at the node is no longer one number and `powershare_C` no longer factors out, so a single node scalar cannot reproduce every collector's income exactly. **That is the whole of the claim, and it is a claim about exactness, not about magnitude.** How large the error is depends on which scalar you substitute for the per-good share, and that choice is not fixed by the design: substituting the share at one arbitrarily chosen reference commodity gives per-collector errors up to **+7.4%** at `sevilla`, and sweeping which commodity is chosen moves that same collector's error across a **17.8-point** range — so those figures measure the arbitrary choice, not the design. Substituting the quantity an implementation would actually store — the **value-weighted mean share** across the node's goods — the error is **at most 0.1%** at every node measured (`sevilla`, `champagne`, `genua`, `malacca`, `gulf_of_siam`). The honest statement is therefore: per-good propagation costs the exact identity and buys a per-node error that a reasonable scalar keeps within a tenth of a percent, and the identity is what Goal 7 is stated in terms of. *(v1 through v4.0 quoted "off by 5.96 ducats on a node paying ~250"; no node in the model has local trade value near 250. v4.0's replacement, 0.41%, and v5.0's "redistributive and single-digit percent" were both artifacts of freezing the share at one commodity — v5.0 having correctly diagnosed exactly that defect in v4.0. The construction behind any such figure — which countries collect, which transfer, and which commodity's share is frozen — has to be stated with it, and none of those documents stated it.)*"""
patch_lib.apply([dict(id="R9-310", clears="D1: exactness not materiality", section="3.10",
                      old=old, new=new)])
